### ISSUE TITLE
Create docker image for stream8 rpmbuild

### ISSUE THREAD

**Issue by jajera** [platformfuzz/image-builder#34]
1. base image based from ghcr.io/platformfuzz/image-builder/stream8:latest
2.  install the following packages
     - dnf-utils
     - rpm-build
     - rpmdevtools

### Tasks:

- [x] Create directory structure.
- [x] Create, configure and test *Dockerfile* file.
- [x] Create *README.md* file.
- [x] Add new build image name to *build-image.yml* list.
