### ISSUE TITLE
Create docker image for ubi8

### ISSUE THREAD

**Issue by jajera** [platformfuzz/image-builder#37]
1. base image based from registry.access.redhat.com/ubi8/ubi:8.8-1067
2. enable epel

### Tasks:

- [x]  Create directory structure.
- [x] Create, configure and test *Dockerfile* file.
- [x] Create *README.md* file.
- [x] Add new build image name to *build-image.yml* list.
