### ISSUE TITLE
Create docker image for ubi8 rpmbuild

### ISSUE THREAD

**Issue by jajera** [platformfuzz/image-builder#39]
1. base image based from ghcr.io/platformfuzz/image-builder/ubi8:latest
2.  install the following packages
     - dnf-utils
     - rpm-build
     - rpmdevtools

### Tasks:

- [ ] Create directory structure.
- [ ] Create, configure and test *Dockerfile* file.
- [ ] Create *README.md* file.
- [ ] Add new build image name to *build-image.yml* list.
